version: '3.1'
services:
  app:
    build: .
    container_name: app
    ports:
      - 9000:9000
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/db_todo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=psw_todo
  postgresqldb:
    image: postgres:13.1-alpine
    container_name: postgresqldb
    ports:
      - 5432:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psw_todo
      - POSTGRES_DB=db_todo